### ISSUE TITLE
Allow directly selecting successors

### ISSUE THREAD

**Issue by floyd-may** [jinaga/jinaga.net#142]
It could be simpler to select successors. Here's the example straight from the docs:

```csharp
var postsInSite = Given<Site>.Match((site, facts) =>
    // Find all posts in this site.
    from post in facts.OfType<Post>()
    where post.site == site
    select new
    {
        hash = jinagaClient.Hash(post),
        // For each post, find all titles.
        titles =
            from title in facts.OfType<PostTitle>()
            where title.post == post
            select title.value
    }
);
```

It should be possible to express this as:
```csharp
var postsInSite = Given<Site>.Match((site, facts) =>
    // Find all posts in this site.
    from post in site.Successors<Post>(post => post.site)
    select new
    {
        hash = post.JinagaHash(),
        // For each post, find all titles.
        titles =
            from title in post.Successors<PostTitle>(title => title.post)
            select title.value
    }
);
```

I propose this because the `from ... where ...` pattern feels like it could be a place where bugs hide. It also reinforces the idea of navigating a historical model's relationships in terms of successor/predecessor.

This would have to be done via extension methods. Also, it would likely need some safeguards for being called outside of a specification, but nothing out of the ordinary for any user of EF Core. Granted this also fits a bit cleaner in the chained method syntax:
```csharp
var postsInSite = Given<Site>.Match((site, facts) =>
    // Find all posts in this site.
    site.Successors<Post>(post => post.site)
        .Select(post => new
    {
        hash = post.JinagaHash(),
        // For each post, find all titles.
        titles = post.Successors<PostTitle>(title => title.post)
                        .Select(title => title.value)
    })
);
```

I like this less than I do [this other issue](https://github.com/jinaga/jinaga.js/issues/99), but maybe worth considering?

**Comment by michaellperry** [comment]
Good suggestion. And it rhymes with your TypeScript suggestion. This seems feasible.

**Comment by michaellperry** [comment]
Upon deeper inspection, the proposed syntax would not work. A revised syntax that would work ended up being very close to an alternate form of 'facts.OfType<T>'. You can optionally pass a predicate into that function as opposed to a separate 'Where'. See Predicate in OfType in [Syntax Alternatives](https://jinaga.net/documents/linq/syntax-alternatives/).

Would this form satisfy the desire for more concise syntax?

**Comment by floyd-may** [comment]
Not really. Looking at the commit above, your test has this:

```csharp
var specification = Given<AirlineDay>.Match((airlineDay, facts) =>
    from flight in facts.Successors<Flight>(f => f.airlineDay == airlineDay)
    select flight
);
 ```

I would have expected the `.Successors(...)` call to be on `airlineDay`, not on `facts`:

```csharp
var specification = Given<AirlineDay>.Match(airlineDay =>
    from flight in airlineDay.Successors<Flight>(f => f.airlineDay)
    select flight
);
 ```

Also, notice that the signature of the parameter to `.Successors(...)` is `Func<Flight, AirlineDay>`, not `Func<Flight, bool>`. The equality check there (IMNSHO) is superfluous - equality is implied. You could even do an overload where the signature is `Func<TSuccessor, IEnumerable<TFact>>` if you want the successor to be matched if _any_ of the facts match (great for array fields).

Thinking through a more complex example, let's say I want to see all the articles that a given author has written, reviewed, or approved:

```
var spec = Given<Author>.Match(author => new {
    author,
    authoredArticles = author
                .Successors<Article>(article => article.Authors),
    reviewedArticles = author
                .Successors<ArticleReviewed>(review => review.Author)
                .Select(review => review.Article),
    approvedArticles = author
                .Successors<ArticleApproved>(approval => approval.Author)
                .Select(approval => approval.Article),
});
```

This to me feels much more concise and intent-revealing.

If you don't absolutely hate the syntax but don't have any more cycles to spend on this, can you leave this issue open and maybe I'll play with it at some point and make a PR?

**Comment by michaellperry** [comment]
After getting the TypeScript variant to work, I think there might be a way forward. This syntax bypasses the `FactRepository`, which is part of the LINQ query provider. I thought that this would be an issue. But after doing essentially the same thing in TypeScript, I realize that it might not in fact be a problem.

Let me take another run at it. I don't want your first experience with Jinaga.NET to be wading through some ugly expression parser code.

**Comment by floyd-may** [comment]
Oh, I don't mind expression parsing code 😉 Didn't we work together on some expression parsing stuff way back in the day?

**Comment by michaellperry** [comment]
I've been playing with type inference. The problem is that we need two generic types, the source (predecessor), and the successor. The source type can be inferred. The successor type must be specified.

Generic type inference is an all-or-nothing proposition. So it's difficult to infer one and specify the other.

I found a couple of solutions. You can see them compared in this [commit diff](https://github.com/jinaga/jinaga.net/pull/145/commits/16c3f87287c654580c6198449b51411f51c0d56c).

First attempt: two method calls. The first one infers a type and the second one specifies it.

```csharp
site.Successors().OfType<Content>(c => c.site)
```

Second attempt: specify the lambda parameter type.

```csharp
site.Successors((Content c) => c.site)
```

I like the second one. Do you think people will know to do this?

BTW, the problem goes away if I just use `object` for the predecessor type, but that allows invalid lambdas.

**Comment by floyd-may** [comment]
I like them both, dangit! 😂 The first one feels a little more idiomatic within chained LINQy code, but there's something charming about the conciseness of the second one. I think people will understand how to do the second one if it's in the docs. I also think the second one will feel more natural in LINQ expression code (`from ... where ... select ...`).

**Comment by michaellperry** [comment]
I have a NuGet package for us to try.

First, you will need to create a personal access token on GitHub and [Authenticate to GitHub Packages](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry#authenticating-to-github-packages). Add the scope `read:packages`.

Then add the package source `https://nuget.pkg.github.com/jinaga/index.json`.

```powershell
dotnet nuget add source "https://nuget.pkg.github.com/jinaga/index.json" --name "Jianga packages" -u "GitHubPAT" -p "yourpersonalaccesstoken"
```

Then install the package.

```powershell
dotnet add package Jinaga --version 1.0.19-g5f9fd2f3bb -s "Jinaga packages"
```

I currently have the extension method in a different namespace so that the `Successors` function doesn't show up in intellisense on everything unless you ask for it. Be sure to add:

```csharp
using Jinaga.Extensions;
```

## Detailed Instructions: Create a Personal Access Token (PAT) on GitHub

1. Go to [GitHub Settings](https://github.com/settings/profile).
2. On the left sidebar, click **Developer settings** > **Personal access tokens** > **Tokens (classic)**.
3. Click **Generate new token**.
4. Provide a note for the token (e.g., “NuGet access for Jinaga packages”).
5. Under **Select scopes**, check the following permissions:
   - `read:packages` (to access GitHub Packages)
6. Click **Generate token** at the bottom of the page.
7. Copy the token and save it securely, as you won’t be able to view it again.

**Comment by michaellperry** [comment]
Things I've noticed so far:
- `Successors` does not work with collections
- There is no equivalently simple way to express existential conditions
- Lambdas are still required to have the `facts` parameter, even if it's not used
- It would be really nice to define an `IQueryable` property directly without using `Relation.Define`

**Comment by michaellperry** [comment]
Here's a new package that addresses some of those issues.

> 1.0.25-gc4de387788

It reintroduces the `Successors().OfType<T>` syntax, because that give me room for the new `Any<T>` and `No<T>` methods. I'm kinda liking it.

Still to address:
- Lambdas are still required to have the `facts` parameter, even if it's not used
- It would be really nice to define an `IQueryable` property directly without using `Relation.Define`

I'm adding to that list:
- Consider a helper to shorten the `Where(p => p.Successors().No<S>(s => s.role))` syntax

Imagine if the `OfType` returned a chainable type that allows something like this:

```csharp
var namesOfPerson = Given<Person>.Match(person =>
 person.Successors().OfType<PersonName>(n => n.person)
    .WhereNo<PersonName>(next => next.prior)
```

**Comment by michaellperry** [comment]
New build that lets you drop the `facts` parameter.

> 1.0.26-g933285292e

**Comment by michaellperry** [comment]
Turns out `Relation.Define` is still required. I've modified it and `Condition.Define` to accept lambdas without parameters. The fact repository is now completely optional.

I also was able to get the `WhereNo` and `WhereAny` methods working. I did that by supporting `IQueryable` to `IQueryable` functions. This makes it possible for app developers to define their own helper functions. I might document some recommended patterns using that technique, like mutable properties, delete, and restore.

Release candidate:

> 1.0.31-g6f1ce21c99

**Comment by michaellperry** [comment]
A couple of things came out of this morning's stream. First, I want better exceptions when using `Successors` in an unsupported way. And second, I want to ship a few patterns in the box. Some patterns include:
- Delete
- Delete and Restore
- Mutable Property
